### ISSUE TITLE
Add use-package configuration in the Readme

### ISSUE THREAD

**Issue by innerout** [rclarey/deno-emacs#1]
Great Job for the package, it would be good to also have a use-package sample configuration since you already have 3 samples(vanilla config,doom and spacemacs).

**Comment by rclarey** [comment]
Thanks! I haven't used use-package myself, but looking at the docs it seems like this would be a minimal example config?
```elisp
(use-package deno-fmt
  :ensure t
  :hook (js2-mode typescript-mode))
```

Figured I would confirm with someone who actually uses use-package before adding it to the readme.

**Comment by innerout** [comment]
The hook macro should be   `:hook (js2-mode . typescript-mode)` and everything should work as expected.

**Comment by innerout** [comment]
@rclarey It seems I was wrong, I did not know about the syntax you proposed. 
The correct way is the one in your example.

**Comment by rclarey** [comment]
I've updated the readme!
