### ISSUE TITLE
Saving a file causes it to jump

### ISSUE THREAD

**Issue by finalclass** [rclarey/deno-emacs#2]
Thanks for a great plugin. I really enjoy using it.

Whenever I save a file it "jumps" in a way that my cursor is placed in the middle of the screen. 

![Peek 2023-01-17 00-10](https://user-images.githubusercontent.com/1343930/212772803-a83233ff-acba-4149-a3c5-3b32b0f75aa0.gif)

Is there any workaround for that?

**Comment by rclarey** [comment]
From what I can tell, more sophisticated formatting minor modes (like go-mode and prettier-mode) will create a diff of the original file and the formatted file, then use that diff to adjust cursor position and scroll position. deno-fmt-mode just stores the cursor offset before formatting, then restores that position after formatting which is what causes the jump I believe.

The fix would be to implement the diffing logic from go-mode or prettier-mode

**Comment by rclarey** [comment]
@finalclass 
I added the diffing logic mentioned above in https://github.com/rclarey/deno-emacs/commit/6378966f448a3b9b5ae98af58cd13a031bd26702 and it seems to be working for me when I tested it briefly. The new version should be reflected in MELPA soon (assuming I didn't mess anything up)

**Comment by finalclass** [comment]
Thanks a lot. It works great.
